// Renders the SVG string diagram_renderer.py (server_py/tools/diagram_renderer.py)
// produces for render_diagram. That module XML-escapes every piece of model-
// supplied text before it's concatenated into the SVG, so this is safe to drop
// into the DOM directly -- the content is generated by our own deterministic
// backend code, not arbitrary external/user-uploaded SVG.
export default function DiagramCard({ diagram }) {
  return (
    <div
      className="lh-chart-card lh-diagram-card"
      style={{
        background: "var(--surface-1)",
        border: "1px solid var(--border)",
        borderRadius: "var(--radius-md)",
        padding: 20,
        marginTop: 8,
        width: "100%",
        maxWidth: 720,
      }}
    >
      {diagram.title && (
        <h3 style={{ margin: "0 0 12px", fontSize: 16, fontWeight: 600, color: "var(--text-primary)" }}>{diagram.title}</h3>
      )}
      <div style={{ display: "flex", justifyContent: "center" }} dangerouslySetInnerHTML={{ __html: diagram.svg }} />
    </div>
  );
}
